name: Build and Test

on:
  push:
    paths:
      - 'src/**'
      - 'build/**'
  pull_request:
    paths:
      - 'src/**'
      - 'build/**'
  workflow_dispatch:

jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            installDir: /usr/share/dotnet
          - os: windows-latest
            installDir: C:\Program Files\dotnet
          - os: macos-latest
            installDir: /Users/runner/.dotnet
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x
        env:
          DOTNET_INSTALL_DIR: ${{ matrix.installDir }}
      - name: Setup .NET 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
        env:
          DOTNET_INSTALL_DIR: ${{ matrix.installDir }}
      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
        env:
          DOTNET_INSTALL_DIR: ${{ matrix.installDir }}
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: True
        env:
          DOTNET_INSTALL_DIR: ${{ matrix.installDir }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Run Tests
        run: dotnet test --configuration Release --no-build